name: Trial

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    name: Trial
    runs-on: [kubernetes-runners-4xmlp-5mhcg]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Echo start message
        shell: bash
        run: |
          echo start workflow!
